"""Core data models for Knowledge Base Builder."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date, datetime
from enum import Enum
from pathlib import Path


class QuestionTopic(str, Enum):
    """Topics for knowledge extraction questions."""

    EDUCATION = "education"
    WORK_EXPERIENCE = "work_experience"
    LIFE_EXPERIENCE = "life_experience"
    SKILL = "skill"
    OPINION = "opinion"
    DECISION = "decision"
    PROCESS = "process"
    GENERAL = "general"


class LLMProviderName(str, Enum):
    """Supported LLM providers."""

    ANTHROPIC = "anthropic"
    OPENAI = "openai"
    OLLAMA = "ollama"


@dataclass
class UserProfile:
    """Structured representation of who the user is."""

    name: str = ""
    education: list[str] = field(default_factory=list)
    work_experience: list[str] = field(default_factory=list)
    life_experience: list[str] = field(default_factory=list)
    interests: list[str] = field(default_factory=list)
    raw_markdown: str = ""
    last_updated: datetime | None = None

    @property
    def summary(self) -> str:
        """Return a concise text summary for LLM context."""
        parts = []
        if self.name:
            parts.append(f"Name: {self.name}")
        if self.education:
            parts.append("Education: " + "; ".join(self.education))
        if self.work_experience:
            parts.append("Work: " + "; ".join(self.work_experience))
        if self.life_experience:
            parts.append("Life experience: " + "; ".join(self.life_experience))
        if self.interests:
            parts.append("Interests: " + "; ".join(self.interests))
        return "\n".join(parts) if parts else self.raw_markdown


@dataclass
class KnowledgeEntry:
    """A single piece of documented knowledge."""

    title: str
    content: str
    topic: QuestionTopic = QuestionTopic.GENERAL
    source: str = "daily_log"  # "daily_log" or "import"
    created_at: date | None = None
    tags: list[str] = field(default_factory=list)

    @property
    def slug(self) -> str:
        """URL-safe slug derived from the title."""
        slug = re.sub(r"[^a-z0-9]+", "-", self.title.lower()).strip("-")
        return slug[:80] if len(slug) > 80 else slug


@dataclass
class DailyLog:
    """A log of one day's question-answer exchange."""

    log_timestamp: datetime
    question: str
    question_topic: QuestionTopic
    question_rationale: str
    response: str
    recorded_entry: str
    slug: str = ""

    def to_markdown(self) -> str:
        """Serialize this daily log to markdown format."""
        ts = self.log_timestamp.strftime("%Y-%m-%d %H:%M")
        return (
            f"# Daily Log — {ts}\n\n"
            f"**Question** ({self.question_topic.value}): {self.question}\n\n"
            f"**Rationale**: {self.question_rationale}\n\n"
            f"## Response\n\n{self.response}\n\n"
            f"## Recorded Knowledge\n\n{self.recorded_entry}\n"
        )


@dataclass
class Question:
    """A question generated by the system for the user."""

    text: str
    topic: QuestionTopic
    rationale: str


@dataclass
class KBBConfig:
    """Application configuration."""

    data_dir: Path | None = None  # Must be provided explicitly via --data-dir or KBB_DATA_DIR
    llm_provider: LLMProviderName = LLMProviderName.ANTHROPIC
    llm_model: str = "claude-sonnet-4-20250514"
    llm_api_key: str = ""
    llm_base_url: str = ""  # Custom endpoint (e.g. Ollama, Azure OpenAI)
    daily_log_time: str = "09:00"
